# Generated by Django 4.2.13 on 2024-05-18 03:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_ledger_wallet_transaction_ledger_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('wallet', 'wallet'), ('account', 'account')], max_length=10)),
                ('read', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboards.dashboard')),
            ],
        ),
    ]
