# Generated by Django 4.2.13 on 2024-05-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_announcement'),
        ('messaging', '0002_conversation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='dashboards.dashboard'),
        ),
    ]
