# Generated by Django 4.2.13 on 2024-05-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_conversationcontrols'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationcontrols',
            old_name='displaying',
            new_name='open',
        ),
    ]
