# Generated by Django 4.2.13 on 2024-05-19 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=3600)),
                ('type', models.CharField(choices=[('account', 'account'), ('system', 'system'), ('season', 'season'), ('story', 'story'), ('store', 'store')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
