# Generated by Django 4.2.13 on 2024-05-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemannouncement',
            name='type',
            field=models.CharField(choices=[('welcome', 'welcome'), ('account', 'account'), ('system', 'system'), ('season', 'season'), ('story', 'story'), ('store', 'store')], max_length=10),
        ),
    ]
