# Generated by Django 4.2.13 on 2024-05-19 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('info', models.CharField(blank=True, max_length=220, null=True)),
                ('value', models.IntegerField(default=0)),
                ('rarity', models.IntegerField(default=0)),
                ('probability', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('control_number', models.PositiveIntegerField(default=0)),
                ('sellable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sets.set')),
            ],
        ),
    ]
