# Generated by Django 4.2.13 on 2024-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_chestbaseitem_collectablebaseitem_consumablebaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='dfg', max_length=120),
            preserve_default=False,
        ),
    ]
