# Generated by Django 4.2.13 on 2024-05-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.CharField(blank=True, default='hjkf', max_length=220),
            preserve_default=False,
        ),
    ]
